import { ITexts } from './types';

export const texts: ITexts[] = [{
    language: 'german',
    info: {
        shortTitleOfTheApp: 'Dance Planner',
        longTitleOfTheApp: 'Fancy Dance Planner',
        location: 'Möchtest Du Tanzevents in Deiner Nähe finden?. Falls ja gib mir bitte 4 Sekunden. Falls Die Seite dann nicht automatisch neu lädt, kann ich aus irgendeinem Grund Deine Position auf der Erde nicht ermitteln.',
        chooseDanceStyle: 'Was möchtest Du tanzen?',
        chooseCity: 'Wo möchtest Du tanzen?',
        whereIsTheEvent: 'Wo findet das Event statt?',
        noMatchFound: 'Zu den eingegeben Daten haben wir aktuell kein Event in unserer Datenbank. Bitte gedulde Dich noch ein paar Wochen. Wir haben den dance-planner.de erst gestartet :)',
        eventsInRange: 'Events im Umkreis von',
        distanceUnitShort: 'km',
        distanceUnitLong: 'Kilometer',
        todayIn: 'Heute in',
        tomorrowIn: 'Morgen in',
        niceYouAreInterested: 'Schön dass Du Dich für dieses Event interessierst.',
        shareTheFollowingLinkWithFriends: 'Teile den folgenden Link gerne mit Deinen Freunden:',
        hereYouFindTheWhatsAppGroup: 'Hier gelangst Du zur WhatsApp Gruppe:',
        hereYouFindTheTelegramGroup: 'Hier gelangst Du zur Telegram Gruppe:',
        createNewEvent: 'Neues Event anlegen',
        createNewVersion: 'Event aktualisieren',
        createEvents: 'Events anlegen',
        contact: 'Kontakt aufnehmen',
        danceAndMusicStyle: 'Tanz- und Musik- Stil',
        date: 'Datum',
        linkToFurtherInfo: 'Link zu weiteren Infos (Optional)',
        telegramLink: 'Telegram Link (Optional)',
        whatsAppLink: 'WhatApp Link (Optional)',
        comments: 'Kommentare (Optional)',
        title: 'Titel Deines Events (Optional)',
        addThisDate: 'Dieses Datum hinzufügen',
        searchEvents: 'Events finden',
        showCitiesWithMinimum: 'Städte anzeigen ab',
        inhabitants: 'Einwohner',
        weekDays: ['Sonntag', 'Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag'],
    },
}, {
    language: 'english',
    info: {
        shortTitleOfTheApp: 'Dance Planner',
        longTitleOfTheApp: 'Fancy Dance Planner',
        location: '',
        chooseDanceStyle: 'Click to choose a dance style',
        chooseCity: 'Click to choose a city',
        whereIsTheEvent: 'Where',
        noMatchFound: 'No data found.',
        eventsInRange: 'Matches in the range of',
        distanceUnitShort: 'km',
        distanceUnitLong: 'Kilometer',
        todayIn: 'Today in',
        tomorrowIn: 'Tomorrow in',
        niceYouAreInterested: 'Nice you are intereste in this match.',
        shareTheFollowingLinkWithFriends: 'Share the following link with your friends:',
        hereYouFindTheWhatsAppGroup: 'WhatsApp group link:',
        hereYouFindTheTelegramGroup: 'Telegram group link:',
        createNewEvent: 'Create a new event',
        createNewVersion: 'Update event',
        createEvents: 'Create events',
        contact: 'Contact',
        danceAndMusicStyle: 'Dance and music style',
        date: 'Date',
        linkToFurtherInfo: 'Link to further information (optional)',
        telegramLink: 'Telegram link (optional)',
        whatsAppLink: 'WhatApp link (optional)',
        comments: 'comments (optional)',
        title: 'title (optional)',
        addThisDate: 'Add this date',
        searchEvents: 'Search events',
        showCitiesWithMinimum: 'Städte anzeigen ab',
        inhabitants: 'inhabitants',
        weekDays: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
},
];
